{{- if .Values.gateway.enabled }}
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-gateway-class
spec:
  nodeSelector:
    {{ toYaml .Values.nodeSelector | indent 8 }}
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  name: {{ .Release.Name }}-gateway
spec:
  gatewayClassName: {{ .Release.Name }}-gateway-class
  addresses:
    - type: IPAddress
      value: {{ .Values.gateway.ip }}
  listeners:
    {{- range .Values.gateway.routes }}
    - name: {{ $.Release.Name }}-{{ .protocol }}
      protocol: {{ upper .protocol }}
      port: {{ .port }}
      allowedRoutes:
        kinds:
          - kind: {{ upper .protocol }}Route
    {{- end }}
{{- range .Values.gateway.routes }}
---
{{- if hasPrefix "tcp" .protocol }}
apiVersion: gateway.networking.k8s.io/v1alpha2
{{- else}}
apiVersion: gateway.networking.k8s.io/v1
{{- end}}
kind: {{ upper .protocol }}Route
metadata:
  name: {{ $.Release.Name }}-{{ .protocol }}
spec:
  parentRefs:
    - name: {{ $.Release.Name }}-gateway
      sectionName: {{ $.Release.Name }}-{{ .protocol }}
  rules:
    - backendRefs:
        - name: {{ $.Release.Name }}-svc
          port: {{ .port }}
  {{- end }}
  {{- end }}