apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  internalTrafficPolicy: Cluster
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol | default "TCP" }}
      targetPort: {{ .targetPort }}
    {{- end}}
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}
{{- if eq "LoadBalancer" .Values.service.type }}
status:
  loadBalancer:
    ingress:
      - ip: {{ .Values.service.ip }}
{{- end }}